add banner
EleonoraPavlova/EleonoraPavlovaDigital-agency pull request #2
Opened 2021-10-07 11:05 UTC by EleonoraPavlova

2021-10-07 11:07 UTC, AndreyBaranov approved these changes

2021-10-07 16:14 UTC, AndreyBaranov commented on src/components/common/ButtonGet/index.js
> +export default function ButtonGet(props) {
я б назва цей компонет не ButtonGet а MoreDetailsButton

2021-10-08 14:48 UTC, AndreyBaranov requested changes

2021-10-08 14:48 UTC, AndreyBaranov commented on src/pages/home/Home.js
>      <div>
тут зайва div

2021-10-08 14:48 UTC, AndreyBaranov commented on src/index.css
> +letter-spacing: 0em;
тут не вистачає табуляцій спочатку

2021-10-08 14:52 UTC, EleonoraPavlova commented on src/pages/home/Home.js
>      <div>
+

2021-10-08 14:54 UTC, merged